#Manifest 
default_events:
  - create
  - issues
  - pull_request
  - pull_request_review
  - pull_request_review_comment

default_permissions:
  checks: read
  contents: read
  issues: write
  metadata: read
  pull_requests: read
  repository_hooks: read
  repository_projects: read
  statuses: read

name: WIPCream
description: Work in progress management application for Github pull requests
public: false
